import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const thai = {
  'Home':'หน้าแรก','About':'เกี่ยวกับฉัน','Skills':'ทักษะ','Experience':'ประสบการณ์','Projects':'ผลงาน','Awards':'รางวัล','Activities':'กิจกรรม','Certificates':'ประกาศนียบัตร','Contact':'ติดต่อ','Computer Engineering':'วิศวกรรมคอมพิวเตอร์',
  'Open to internship opportunities':'เปิดรับโอกาสฝึกงาน','Hello, I’m':'สวัสดีค่ะ ฉันชื่อ','Computer Engineering Student':'นักศึกษาวิศวกรรมคอมพิวเตอร์',
  'Building practical solutions through software, IoT, and engineering.':'สร้างโซลูชันที่ใช้งานได้จริงผ่านซอฟต์แวร์ IoT และวิศวกรรม',
  'Explore my projects':'ดูผลงานของฉัน','Download resume':'ดาวน์โหลดเรซูเม่','Bangkok, Thailand':'กรุงเทพฯ ประเทศไทย','Email Jirasudanee':'ส่งอีเมลถึงจิรสุดาณี',
  'THE ENGINEER BEHIND THE CODE':'วิศวกรเบื้องหลังโค้ด','COMPUTER ENGINEERING':'วิศวกรรมคอมพิวเตอร์','Software meets the physical world.':'เมื่อซอฟต์แวร์เชื่อมต่อกับโลกจริง','SCROLL TO EXPLORE':'เลื่อนเพื่อดูผลงาน',
  'A LITTLE ABOUT ME':'เกี่ยวกับฉัน','Curious mind.':'ช่างสงสัย','Practical approach.':'ลงมือทำจริง',
  'I’m a fourth-year Computer Engineering student at Sripatum University, bringing together frontend development, IoT systems, and a hands-on approach to problem solving.':'ฉันเป็นนักศึกษาวิศวกรรมคอมพิวเตอร์ชั้นปีที่ 4 มหาวิทยาลัยศรีปทุม มีประสบการณ์ด้านการพัฒนา Frontend ระบบ IoT และการแก้ปัญหาผ่านการลงมือทำจริง',
  'From an industry-partnered energy audit system to award-winning engineering research, I enjoy turning what I learn into practical projects—with a team, a purpose, and room to improve.':'ตั้งแต่ระบบตรวจประเมินการใช้พลังงานร่วมกับภาคอุตสาหกรรม ไปจนถึงงานวิจัยวิศวกรรมที่ได้รับรางวัล ฉันสนุกกับการนำความรู้มาพัฒนาเป็นโครงการจริง ร่วมกับทีมและเป้าหมายที่ชัดเจน',
  'More about my education':'ดูข้อมูลการศึกษา','SRIPATUM UNIVERSITY':'มหาวิทยาลัยศรีปทุม','Cumulative GPA':'เกรดเฉลี่ยสะสม','Frontend':'ฟรอนต์เอนด์','IoT systems':'ระบบ IoT',
  'SELECTED WORK':'ผลงานเด่น','Ideas, engineered':'เปลี่ยนแนวคิด','into something real.':'ให้กลายเป็นผลงานจริง','A selection of industry collaborations, connected systems, and hands-on engineering.':'ผลงานที่คัดสรรจากความร่วมมือกับภาคอุตสาหกรรม ระบบเชื่อมต่อ และการลงมือทำด้านวิศวกรรม',
  'FEATURED PROJECT':'โปรเจกต์เด่น','IoT system':'ระบบ IoT','Real-time alerts':'แจ้งเตือนเรียลไทม์','Research':'งานวิจัย','3 recognitions across innovation & research':'3 รางวัลด้านนวัตกรรมและงานวิจัย','View details':'ดูรายละเอียด','Close project details':'ปิดรายละเอียดโปรเจกต์',
  'My role':'บทบาทของฉัน','Key contribution':'สิ่งที่มีส่วนร่วม','Project areas':'ขอบเขตโครงการ','Recognition':'รางวัลและการยอมรับ',
  'MY TOOLKIT':'ทักษะของฉัน','Built on a technical foundation.':'ต่อยอดจากพื้นฐานทางเทคนิค','From interfaces and databases to circuits and connected hardware.':'ตั้งแต่ส่วนติดต่อผู้ใช้และฐานข้อมูล ไปจนถึงวงจรและฮาร์ดแวร์ที่เชื่อมต่อกัน',
  'THE JOURNEY SO FAR':'เส้นทางที่ผ่านมา','Learning by doing.':'เรียนรู้ผ่านการลงมือทำ',
  'RECOGNITION':'รางวัลและความสำเร็จ','Hard work. Shared achievements.':'ความทุ่มเทที่สร้างความสำเร็จร่วมกัน','Recognitions earned together through engineering, innovation, and research.':'ความสำเร็จจากการทำงานร่วมกันผ่านวิศวกรรม นวัตกรรม และงานวิจัย',
  'EDUCATION':'การศึกษา','Engineering my future.':'สร้างอนาคตด้วยวิศวกรรม','2023 – PRESENT':'2023 – ปัจจุบัน','Bachelor of Engineering':'วิศวกรรมศาสตรบัณฑิต','Expected graduation: 2026':'คาดว่าจะสำเร็จการศึกษา: 2026','CUMULATIVE GPA':'เกรดเฉลี่ยสะสม','100% tuition credit fee scholarship':'ทุนยกเว้นค่าหน่วยกิต 100%','Four semesters · Selected as the faculty’s sole recipient':'4 ภาคการศึกษา · ได้รับคัดเลือกเพียงคนเดียวของคณะ',
  'BEYOND THE CODE':'มากกว่าเรื่องโค้ด','Better, together.':'เติบโตไปด้วยกัน','Sharing knowledge, bringing people together, and finding a voice beyond the workbench.':'แบ่งปันความรู้ เชื่อมโยงผู้คน และพัฒนาทักษะการสื่อสารนอกเหนือจากงานด้านเทคนิค',
  'CONTINUOUS LEARNING':'การเรียนรู้อย่างต่อเนื่อง','Credentials & certifications.':'ประกาศนียบัตรและใบรับรอง',
  'LET’S CONNECT':'มารู้จักกัน','Let’s build something':'มาร่วมสร้างสิ่งที่','meaningful.':'มีความหมาย','Looking for an engineering intern with curiosity, initiative, and a hands-on mindset? Let’s talk.':'กำลังมองหานักศึกษาฝึกงานด้านวิศวกรรมที่ใฝ่รู้ มีความคิดริเริ่ม และพร้อมลงมือทำอยู่หรือเปล่า มาคุยกันค่ะ','Send an email':'ส่งอีเมล',
  'Designed & Built by Jirasudanee':'ออกแบบและพัฒนาโดย Jirasudanee','Back to home':'กลับหน้าแรก','Back to top':'กลับด้านบน','Open navigation':'เปิดเมนู','Close navigation':'ปิดเมนู','Switch to Thai':'เปลี่ยนเป็นภาษาไทย','Switch to English':'เปลี่ยนเป็นภาษาอังกฤษ','Switch to light mode':'เปลี่ยนเป็นโหมดสว่าง','Switch to dark mode':'เปลี่ยนเป็นโหมดมืด','Skip to content':'ข้ามไปยังเนื้อหา','Main navigation':'เมนูหลัก','Display preferences':'การตั้งค่าการแสดงผล','Jirasudanee home':'หน้าแรกของ Jirasudanee',

  'Programming':'การเขียนโปรแกรม','Web development':'การพัฒนาเว็บ','Databases':'ฐานข้อมูล','Hardware & IoT':'ฮาร์ดแวร์และ IoT','Hardware description':'ภาษาบรรยายฮาร์ดแวร์','How I work':'ทักษะการทำงาน','Frontend development':'การพัฒนา Frontend','Circuit design':'การออกแบบวงจร','Sensor integration':'การเชื่อมต่อเซนเซอร์','Microcontroller programming':'การเขียนโปรแกรมไมโครคอนโทรลเลอร์','IoT development':'การพัฒนา IoT','Team communication':'การสื่อสารในทีม','Collaboration':'การทำงานร่วมกัน','Leadership & coordination':'ภาวะผู้นำและการประสานงาน','Critical thinking':'การคิดวิเคราะห์','Problem solving':'การแก้ปัญหา','Teamwork':'การทำงานเป็นทีม','Leadership':'ภาวะผู้นำ','Teaching':'การสอน','Coordination':'การประสานงาน','Industry collaboration':'ความร่วมมือกับอุตสาหกรรม','Industrial monitoring':'การติดตามภาคอุตสาหกรรม','Augmented reality':'เทคโนโลยี AR','Field testing':'การทดสอบภาคสนาม','Condition monitoring':'การติดตามสภาพเครื่องจักร','Real-time monitoring':'การติดตามแบบเรียลไทม์','Industrial IoT':'Industrial IoT',

  'IoT · Research':'IoT · งานวิจัย','Frontend · Industry':'Frontend · อุตสาหกรรม','AI · Industrial IoT':'AI · Industrial IoT','AR · Cultural innovation':'AR · นวัตกรรมวัฒนธรรม','Connecting sensors. Creating awareness.':'เชื่อมต่อเซนเซอร์ สร้างการรับรู้',
  'An IoT earthquake monitoring and alert system with real-time notifications through a mobile application.':'ระบบ IoT สำหรับติดตามและแจ้งเตือนแผ่นดินไหวแบบเรียลไทม์ผ่านแอปพลิเคชันบนมือถือ',
  'Team contributor & research co-author':'สมาชิกทีมและผู้ร่วมเขียนงานวิจัย','Contributed to system development, co-authored related research, prepared exhibition materials, and presented the project in English and to competition judges.':'ร่วมพัฒนาระบบ เขียนงานวิจัย จัดเตรียมสื่อสำหรับนิทรรศการ และนำเสนอผลงานเป็นภาษาอังกฤษต่อคณะกรรมการ',
  'Silver Medal · I-New Gen 2026':'เหรียญเงิน · I-New Gen 2026','Second Runner-up · ASCN & SUN Thailand 2026':'รองชนะเลิศอันดับ 2 · ASCN & SUN Thailand 2026','Best Paper · EENET 2026':'บทความดีเด่น · EENET 2026',
  'Frontend interfaces for energy audits and energy-use assessment, developed through an industry-partnered program.':'ส่วนติดต่อผู้ใช้สำหรับการตรวจประเมินและวิเคราะห์การใช้พลังงาน พัฒนาผ่านโครงการร่วมกับภาคอุตสาหกรรม','Frontend development · SID-EN':'พัฒนา Frontend · SID-EN','Developed user interfaces and incorporated user requirements and team feedback in a real industry working environment through the Innovator Journey Program.':'พัฒนาส่วนติดต่อผู้ใช้และนำความต้องการของผู้ใช้รวมถึงข้อเสนอแนะจากทีมมาปรับปรุง ภายใต้สภาพแวดล้อมการทำงานจริงในโครงการ Innovator Journey','Energy assessment':'การประเมินพลังงาน',
  'An AI and Industrial IoT platform for monitoring motor condition and supporting maintenance planning.':'แพลตฟอร์ม AI และ Industrial IoT สำหรับติดตามสภาพมอเตอร์และสนับสนุนการวางแผนบำรุงรักษา','Team member · SITTUI':'สมาชิกทีม · SITTUI','Contributed to the team’s development of a motor condition monitoring and maintenance-planning platform.':'ร่วมกับทีมพัฒนาแพลตฟอร์มติดตามสภาพมอเตอร์และวางแผนการบำรุงรักษา','Best Project · Industrial IoT Tech-Creator Challenges 2026':'รางวัลโครงการยอดเยี่ยม · Industrial IoT Tech-Creator Challenges 2026',
  'A collaborative game project connecting technology with Ayutthaya’s culture and history.':'โครงการเกมที่ผสานเทคโนโลยีกับวัฒนธรรมและประวัติศาสตร์ของพระนครศรีอยุธยา','Project contributor · Silvora':'ผู้ร่วมพัฒนาโครงการ · Silvora','Participated in developing the project and in on-site testing in Ayutthaya during October 2025.':'ร่วมพัฒนาโครงการและทดสอบผลงานจริงในพื้นที่จังหวัดพระนครศรีอยุธยา ช่วงเดือนตุลาคม 2025','National Best Practice recognition · MHESI':'รางวัล Best Practice ระดับชาติ · อว.',

  'May 2026 – Present':'พฤษภาคม 2026 – ปัจจุบัน','Frontend Development':'การพัฒนา Frontend','SID-EN · Innovator Journey Program':'SID-EN · โครงการ Innovator Journey','Developing the Energy Audit System’s frontend for energy-use assessment, translating user requirements and team feedback into interface improvements.':'พัฒนา Frontend ของระบบตรวจประเมินการใช้พลังงาน โดยนำความต้องการของผู้ใช้และข้อเสนอแนะจากทีมมาปรับปรุงส่วนติดต่อผู้ใช้',
  'June – September 2025':'มิถุนายน – กันยายน 2025','Industry Project Participant':'ผู้เข้าร่วมโครงการภาคอุตสาหกรรม','VT Innovative Alliances Co., Ltd. · Innovator Journey':'VT Innovative Alliances Co., Ltd. · Innovator Journey','Collaborated on a factory dust-monitoring device to support industrial green transformation, gaining hands-on experience with industry teams and project delivery.':'ร่วมพัฒนาอุปกรณ์ตรวจวัดฝุ่นในโรงงานเพื่อสนับสนุนการเปลี่ยนผ่านสู่อุตสาหกรรมสีเขียว พร้อมเรียนรู้การทำงานกับทีมอุตสาหกรรมและการส่งมอบโครงการจริง',
  'President, AIoT Club':'ประธานชมรม AIoT','Sripatum University':'มหาวิทยาลัยศรีปทุม','Led introductory programming sessions for first-year students. Coordinated task allocation, teaching materials, equipment, and IoT demonstrations for university activities.':'วางแผนและจัดกิจกรรมสอนเขียนโปรแกรมเบื้องต้นสำหรับนักศึกษาชั้นปีที่ 1 พร้อมประสานงาน แบ่งหน้าที่ จัดเตรียมสื่อ อุปกรณ์ และการสาธิตระบบ IoT',
  'Silver Medal':'เหรียญเงิน','I-New Gen Award':'I-New Gen Award','Second Runner-up':'รองชนะเลิศอันดับ 2','Best Paper':'บทความดีเด่น','EENET · Computer and Information Technology':'EENET · ด้านคอมพิวเตอร์และเทคโนโลยีสารสนเทศ','QuakeLink research':'งานวิจัย QuakeLink','Best Project':'โครงการยอดเยี่ยม','Industrial IoT Tech-Creator Challenges':'Industrial IoT Tech-Creator Challenges',
  'Leading the next generation':'ส่งต่อความรู้สู่รุ่นต่อไป','AIoT Club · 2025':'ชมรม AIoT · 2025','Planned and taught introductory programming sessions for first-year students as AIoT Club president.':'วางแผนและสอนการเขียนโปรแกรมเบื้องต้นแก่นักศึกษาชั้นปีที่ 1 ในฐานะประธานชมรม AIoT','Taking research to the stage':'นำงานวิจัยสู่เวที','EENET · May 2026':'EENET · พฤษภาคม 2026','Presented co-authored research on a real-time earthquake monitoring and mobile alert network.':'นำเสนอบทความวิจัยที่ร่วมเขียนเกี่ยวกับเครือข่ายตรวจวัดแผ่นดินไหวและแจ้งเตือนผ่านมือถือแบบเรียลไทม์','Connecting the AIoT community':'เชื่อมโยงชุมชน AIoT','AIoT Foresight & Transformation · March 2026':'AIoT Foresight & Transformation · มีนาคม 2026','Served as emcee at an event marking academic cooperation between SPU and the Thai IoT Association.':'ทำหน้าที่พิธีกรในงานความร่วมมือทางวิชาการระหว่างมหาวิทยาลัยศรีปทุมและสมาคมไทยไอโอที',
  'IT Specialist: Cybersecurity':'IT Specialist: Cybersecurity','ICDL Certificate':'ประกาศนียบัตร ICDL','Spreadsheets · Microsoft Excel 2016':'Spreadsheets · Microsoft Excel 2016',
  'Portrait of Jirasudanee Oakkharasinthirawut':'ภาพถ่ายของจิรสุดาณี อัครสินธีรวุฒิ','QuakeLink team presenting their project at the I-New Gen exhibition':'ทีม QuakeLink นำเสนอผลงานในนิทรรศการ I-New Gen','Industry project team presenting the Energy Audit System at SID-EN':'ทีมโครงการภาคอุตสาหกรรมนำเสนอระบบ Energy Audit ที่ SID-EN','SITTUI team receiving the Best Project award at Industrial IoT Tech-Creator Challenges':'ทีม SITTUI รับรางวัลโครงการยอดเยี่ยมจาก Industrial IoT Tech-Creator Challenges','Silvora project team during their Ayutthaya field visit':'ทีมโครงการ Silvora ระหว่างการลงพื้นที่จังหวัดพระนครศรีอยุธยา','Jirasudanee teaching an introductory programming session':'จิรสุดาณีสอนกิจกรรมเขียนโปรแกรมเบื้องต้น','Jirasudanee presenting QuakeLink research at EENET':'จิรสุดาณีนำเสนองานวิจัย QuakeLink ในงาน EENET','Presenters at the AIoT Foresight and Transformation event':'ผู้ดำเนินรายการในงาน AIoT Foresight and Transformation'
};

const PreferencesContext = createContext(null);

export function PreferencesProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('portfolio-language') || 'en');
  const [theme, setTheme] = useState(() => localStorage.getItem('portfolio-theme') || 'dark');
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dataset.theme = theme;
    localStorage.setItem('portfolio-language', language);
    localStorage.setItem('portfolio-theme', theme);
    const isThai = language === 'th';
    document.title = isThai ? 'Jirasudanee Oakkharasinthirawut | Portfolio วิศวกรรมคอมพิวเตอร์' : 'Jirasudanee Oakkharasinthirawut | Computer Engineering Portfolio';
    document.querySelector('meta[name="theme-color"]')?.setAttribute('content', theme === 'dark' ? '#07111f' : '#f4f8fb');
  }, [language, theme]);
  const value = useMemo(() => ({ language, theme, setLanguage, setTheme, tr: value => language === 'th' ? (thai[value] || value) : value }), [language, theme]);
  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() { return useContext(PreferencesContext); }
